version: '3.9'

services:
  api1: &api
    build: .
    container_name: api1
    environment:
      - RUBY_YJIT_ENABLE=1
      - USE_POOL=1
      - DB_POOL_SIZE=5
      - WEB_CONCURRENCY=5
      - THREAD_POOL=0:5
    command: rackup
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.9GB'

  api2: 
    <<: *api
    container_name: api2

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1GB'

  nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.2GB'
volumes:
  rubygems:
